apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 8081
          protocol: TCP
        env:
          - name: ME_CONFIG_OPTIONS_EDITORTHEME
            valueFrom:
              configMapKeyRef:
                name: myconfigmap
                key: mongoexpress-theme
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: myconfigmap
                key: mongodb-server
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongodb-root-username
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongodb-root-password
---
kind: Service
apiVersion: v1
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  ports:
  - protocol: TCP
    port:  8080
    targetPort:  8081