apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nginx
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /data/disk1


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ngix-local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi


---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - "/bin/sh"
    args: 
      - "-c"
      - "sleep 600"
    volumeMounts:
    - name: local-vol
      mountPath: /var/data
  volumes:
  - name: local-vol
    persistentVolumeClaim:
      claimName: pvc-ngix-local

  